=== marvpaul/VertSys/Task5/booking.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="bookings" type="bookings" />
    
<!-- Bookings -->
<xs:complexType name="bookings">
    <xs:sequence>
        <xs:element name="booking" type="booking" maxOccurs="unbounded"/>
    </xs:sequence>
</xs:complexType>
    
<!-- Booking-->
<xs:complexType name="booking">
    <xs:sequence>
        <xs:element name="flights" type="flights"/>
        <xs:element name="price" type="xs:float"/>
    </xs:sequence>
    <xs:attribute name="booking_nr" type="xs:integer" use="required"/>
</xs:complexType>

<!--Flights-->
<xs:complexType name="flights">
    <xs:sequence>
        <xs:element name="flight" type="flight" maxOccurs="unbounded"/>
    </xs:sequence>
</xs:complexType>

<!--Flight-->
<xs:complexType name="flight">
    <xs:sequence>
        <xs:element name="departure" type="xs:string"/>
        <xs:element name="destination" type="xs:string"/>
        <xs:element name="departure_date" type="xs:date"/>
        <xs:element name="destination_date" type="xs:date"/>
        <xs:element name="departure_time" type="xs:time"/>
        <xs:element name="destination_time" type="xs:time"/>
        <xs:element name="is_secure_flight" type="xs:boolean"/>
        <xs:element name="passengers" type="passengers"/>
    </xs:sequence>
    <xs:attribute name="flight_nr" type="xs:integer" use="required"/>
</xs:complexType>
    
<!-- Passengers -->
<xs:complexType name="passengers">
    <xs:sequence>
        <xs:element name="passenger" type="passenger" maxOccurs="unbounded"/>
    </xs:sequence>
</xs:complexType>

<!-- Passenger-->
<xs:complexType name="passenger">
    <xs:sequence>
        <xs:element name="adress" type="xs:string"/>
        <xs:element name="children" type="xs:integer"/>
    </xs:sequence>
    <xs:attribute name="name" type="xs:string" use="required"/>
</xs:complexType>
</xs:schema>

=== marvpaul/VertSys/Task5/booking.xml
<?xml version="1.0" encoding="utf-8"?>
<bookings xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="booking.xsd">
    <booking booking_nr="123">
        <flights>
            <flight flight_nr="1234">
                <departure>Berlin SFX</departure>
                <destination>Berlin TXL</destination>
                <departure_date>1970-03-27</departure_date>
                <destination_date>1970-03-27</destination_date>
                <departure_time>20:30:10</departure_time>
                <destination_time>21:30:10</destination_time>
                <is_secure_flight>true</is_secure_flight>
                <passengers>
                    <passenger name="Peter Lustig">
                        <adress>Steinweg 18</adress>
                        <children>2</children>
                    </passenger>
                    <passenger name="Felix Lustig">
                        <adress>Steinweg 18</adress>
                        <children>2</children>
                    </passenger>
                    <passenger name="Karl Lustig">
                        <adress>Steinweg 18</adress>
                        <children>2</children>
                    </passenger>
                </passengers>
            </flight>
        </flights>
        <price>40.0</price>
    </booking>
    <booking booking_nr="124">
        <flights>
            <flight flight_nr="1235">
                <departure>Berlin SFX</departure>
                <destination>Berlin TXL</destination>
                <departure_date>1970-03-27</departure_date>
                <destination_date>1970-03-27</destination_date>
                <departure_time>20:30:10</departure_time>
                <destination_time>21:30:10</destination_time>
                <is_secure_flight>true</is_secure_flight>
                <passengers>
                    <passenger name="Peter Lustig">
                        <adress>Steinweg 18</adress>
                        <children>2</children>
                    </passenger>
                </passengers>
            </flight>
            <flight flight_nr="1236">
                <departure>Berlin TXL</departure>
                <destination>London STD</destination>
                <departure_date>1970-03-27</departure_date>
                <destination_date>1970-03-27</destination_date>
                <departure_time>20:30:10</departure_time>
                <destination_time>21:30:10</destination_time>
                <is_secure_flight>false</is_secure_flight>
                <passengers>
                    <passenger name="Marie Green">
                        <adress>Elefantenweg 18</adress>
                        <children>2</children>
                    </passenger>
                </passengers>
            </flight>
        </flights>
        <price>1000.50</price>
    </booking>
    <booking booking_nr="125">
        <flights>
            <flight flight_nr="1240">
                <departure>Berlin TXL</departure>
                <destination>Barcelona DHD</destination>
                <departure_date>1970-03-27</departure_date>
                <destination_date>1970-03-27</destination_date>
                <departure_time>20:30:10</departure_time>
                <destination_time>21:30:10</destination_time>
                <is_secure_flight>true</is_secure_flight>
                <passengers>
                    <passenger name="Felix Eckerkt">
                        <adress>Steinweg 18</adress>
                        <children>0</children>
                    </passenger>
                </passengers>
            </flight>
        </flights>
        <price>440.0</price>
    </booking>
    <booking booking_nr="126">
        <flights>
            <flight flight_nr="1241">
                <departure>Berlin TXL</departure>
                <destination>Reykjavik RKI</destination>
                <departure_date>1970-03-27</departure_date>
                <destination_date>1970-03-27</destination_date>
                <departure_time>20:30:10</departure_time>
                <destination_time>21:30:10</destination_time>
                <is_secure_flight>true</is_secure_flight>
                <passengers>
                    <passenger name="Manuel Ewert">
                        <adress>Mauerplatz 18</adress>
                        <children>10</children>
                    </passenger>
                </passengers>
            </flight>
        </flights>
        <price>50.0</price>
    </booking>
    <booking booking_nr="127">
        <flights>
            <flight flight_nr="1242">
                <departure>Berlin TXL</departure>
                <destination>Reykjavik RKI</destination>
                <departure_date>1970-03-27</departure_date>
                <destination_date>1970-03-27</destination_date>
                <departure_time>20:30:10</departure_time>
                <destination_time>21:30:10</destination_time>
                <is_secure_flight>true</is_secure_flight>
                <passengers>
                    <passenger name="Manuel Mattew">
                        <adress>Mareinstra√üe 10</adress>
                        <children>0</children>
                    </passenger>
                </passengers>
            </flight>
        </flights>
        <price>156.0</price>
    </booking>
</bookings>
